### ISSUE TITLE
Request Make this into an article template

### ISSUE THREAD

**Issue by mathisloevenich** [martinhelso/OsloMet#5]
Hey this is not an issue and rather a request, but I found this template really useful and I am using some of the features now to write an article.

It would be nice if there would be a template for this as well.

**Comment by bjornestol** [comment]
Hi!

I am unsure what you mean/want by turning this into an article template. What are some examples of what you want?

**Comment by mathisloevenich** [comment]
Well at the moment it's only possible to use this beamer template for presentations.
However it would be nice to have an other template for articles, papers, etc. as well (dinA4).

Maybe for a seperate project but I was not able to find anything like that so I thought if I open this Issue here, it will be considered to provide a template for articler as well

**Comment by bjornestol** [comment]
Not sure what you want from this beamer template added to your articles, but this project will stay just as a beamer template.
