### ISSUE TITLE
Permission to use for my University 

### ISSUE THREAD

**Issue by mora200217** [martinhelso/OsloMet#6]
Incredible work! I want to use this base style for my college presentation. Obviously giving the respective credits. Got one question though. Where do you define the Name of the university ? I do not see it.

**Comment by martinhelso** [comment]
Hi! Feel free to use and change the template as you see fit.

All references to the name of the University are made through logo files: `OM-logo.pdf` and `OM-signature.pdf` in `/OM-images`.
